'use strict';
const $=(s,root=document)=>root.querySelector(s), $$=(s,root=document)=>[...root.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const icon=(name,alt='')=>`<img class="asset" src="assets/${name}.svg" alt="${alt}">`;
const authIcon=(name,alt)=>`<img class="auth-icon" src="assets/auth-${name}.svg" alt="${alt}">`;
const modal=$('#modal');let modalTimer=null;let returnFocus=null;
function closeModal(){clearTimeout(modalTimer);modal.close();returnFocus?.focus()}
function openModal(html){clearTimeout(modalTimer);returnFocus=document.activeElement;modal.innerHTML=`<button class="close" aria-label="Close dialog">×</button>${html}`;$('.close',modal).onclick=closeModal;if(!modal.open)modal.showModal()}
modal.addEventListener('cancel',()=>clearTimeout(modalTimer));
function info(topic){const text={docs:['How this prototype works','Sign in opens the portal directly. Sign up walks through five steps: account type, account access, social verification, profile, and preferences. All verification is simulated. Any six digits work for the email code.'],Terms:['Demo terms','This is a local onboarding prototype. It creates no real account, sends no email, and makes no social connection.'],Privacy:['Your demo data','Form values stay in this browser tab’s memory. Refreshing clears the onboarding flow. Profile images are previewed locally and are never uploaded.'],Help:['Need a hand?','Sign in with email or a mock Google account to open the portal directly. For email sign-up, enter any six-digit code. During onboarding, select a social channel, set up your profile, and choose up to three verticals. Wallet connections are simulated.']};let [title,body]=text[topic]||text.docs;openModal(`<h2>${title}</h2><p>${body}</p><button class="primary full" id="got-it">Got it</button>`);$('#got-it').onclick=closeModal}
function toast(text){$('.toast')?.remove();let e=document.createElement('div');e.className='toast';e.role='status';e.textContent=text;document.body.append(e);setTimeout(()=>e.remove(),2600)}
if(document.body.classList.contains('landing')){
 $$('[data-role]').forEach(b=>b.onclick=()=>{let brand=b.dataset.role==='project';$$('[data-role]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));$$('.enter').forEach(x=>x.href=brand?'project-onboarding.html':'creator-onboarding.html');$('#headline').innerHTML=brand?'Your project deserves<br><span>more than attention.</span>':'Your creativity deserves<br><span>more than impressions.</span>';$('#hero-copy').innerHTML=brand?'Connect with Web3 creators, launch campaigns, and turn<br>authentic contributions into measurable growth.':'Find Web3 campaigns, create content, and turn verified<br>contributions into rewards.';$('#why').textContent=brand?'WHY ALLWEB3 FOR BRANDS':'WHY ALLWEB3 FOR CREATORS';$('#feature-title').innerHTML=brand?'Your vision has<br>potential.<br><em>Make it grow.</em>':'Your work has<br>value.<br><em>Make it count.</em>';$('#feature-text').textContent=brand?'AllWeb3 connects your project to the right creators, with clear campaign goals, verified contributions, and visible results.':'AllWeb3 connects your content to campaigns with clear tasks, visible performance, and rewards tied to what you deliver.';$('#showcase-title').textContent=brand?'Grow':'Earn';$('#showcase-copy').textContent=brand?'Build authentic momentum with creators who understand your project and community.':'Get rewarded for the content you create, the results you drive, and the work you deliver.'});$('.theme').onclick=()=>document.body.classList.toggle('light');$('[data-info]').onclick=()=>info('docs');
}else{
 const state={role:document.body.dataset.initialRole,step:0,mode:'signin',email:'',method:'Email',socialLinks:{},profiles:{creator:{name:'',bio:'',website:'',avatar:'',color:''},project:{name:'',bio:'',website:'',avatar:'',color:''}},prefs:{creator:{areas:[],wallet:null},project:{areas:[],wallet:null,goal:'Brand awareness'}}};
 const steps=['Account type','Account access','Social verification','Profile setup','Preferences'];const areaOptions=['DeFi','NFTs','Gaming','Trading','L2 Solutions','Infra','Metaverse','DAO Governance'];const walletProviders=['MetaMask','Coinbase Wallet','WalletConnect'];
 const profile=()=>state.profiles[state.role],prefs=()=>state.prefs[state.role],isProject=()=>state.role==='project';
 const isSigninAccess=()=>state.mode==='signin'&&state.step===0;
 const isAccessStep=()=>isSigninAccess()||(state.mode==='signup'&&state.step===1);
 const mockSocialConnection=platform=>{const brand=isProject();return{'X / Twitter':{handle:brand?'@AllWeb3Demo':'@creator_demo',followers:brand?'12.4K followers':'8.2K followers'},LinkedIn:{handle:brand?'AllWeb3 Demo Brand':'Alex Creator',followers:brand?'3.1K followers':'1.8K followers'},YouTube:{handle:brand?'AllWeb3 Official':'Creator Demo Channel',followers:brand?'28K subscribers':'15K subscribers'}}[platform]};
 const socialCardConfig=(platform,brand)=>({'X / Twitter':{slug:'x',pitch:brand?'Brand voice & updates':'Reach & engagement',desc:brand?'Verify your project’s official channel.':'Connect your reach, content, and audience.'},LinkedIn:{slug:'linkedin',pitch:brand?'Company credibility':'Professional network',desc:brand?'Link your organization’s LinkedIn presence.':'Connect your professional profile.'},YouTube:{slug:'youtube',pitch:brand?'Channel authority':'Video audience',desc:brand?'Verify your official YouTube channel.':'Connect your content and subscribers.'}})[platform];
 function socialVerificationHTML(brand){const order=brand?['X / Twitter','LinkedIn','YouTube']:['X / Twitter','YouTube','LinkedIn'];const connected=Object.keys(state.socialLinks).length;return`<div class="step-callout"${connected?'':' data-empty="true"'}><span class="step-callout-title">${connected?`${connected} channel${connected>1?'s':''} connected`:'Connect at least one channel'}</span><span class="step-callout-sub">${connected?'Add more channels or continue when you’re ready.':'Pick a platform below to verify your presence.'}</span></div><div class="social-card-list">${order.map(platform=>{const cfg=socialCardConfig(platform,brand),link=state.socialLinks[platform];if(link)return`<div class="choice social-choice social-card social-card--${cfg.slug} connected"><div class="social-card-top"><span class="social-brand-badge">${authIcon(cfg.slug,platform)}</span><div class="social-card-intro"><strong>${platform}</strong><span class="social-card-pitch">${cfg.pitch}</span></div><span class="social-pill social-pill--connected">${icon('check','')} Connected</span></div><div class="social-stats"><div class="social-stat"><span class="social-stat-label">Account</span><span class="social-stat-value">${esc(link.handle)}</span></div><div class="social-stat"><span class="social-stat-label">Reach</span><span class="social-stat-value">${esc(link.followers)}</span></div></div><button type="button" class="secondary destructive social-card-btn" data-social-disconnect="${platform}">Disconnect</button></div>`;return`<div class="choice social-choice social-card social-card--${cfg.slug}"><div class="social-card-top"><span class="social-brand-badge">${authIcon(cfg.slug,platform)}</span><div class="social-card-intro"><strong>${platform}</strong><span class="social-card-pitch">${cfg.pitch}</span></div><span class="social-pill">Not connected</span></div><p class="social-card-desc">${cfg.desc}</p><button type="button" class="secondary social-card-btn" data-social-connect="${platform}">Connect</button></div>`}).join('')}</div><p class="hint">Verification is simulated · no real OAuth permissions.</p>`}
 function accountTypeHTML(){const cards=[{id:'creator',title:'Creator Profile',pitch:'Campaigns, content & rewards',copy:'Discover campaigns, share your creativity, and earn rewards for verified contributions.',glyph:'♙',accent:'creator'},{id:'project',title:'Project Profile',pitch:'Creators, campaigns & growth',copy:'Represent your brand, connect with creators, and launch campaigns that grow your community.',glyph:'♧',accent:'project'}];return`<div class="account-type-list">${cards.map(c=>`<button type="button" class="choice account-type-card account-type-card--${c.accent} ${state.role===c.id?'selected':''}" data-account="${c.id}" aria-pressed="${state.role===c.id}"><span class="account-type-glyph" aria-hidden="true">${c.glyph}</span><div class="account-type-copy"><strong>${c.title}</strong><span class="account-type-pitch">${c.pitch}</span><p>${c.copy}</p></div>${state.role===c.id?`<span class="check">${icon('check')}</span>`:''}</button>`).join('')}</div><p class="hint">Your landing page selection is preselected. You can change it here.</p>`}
 function profileSetupHTML(brand,p){const bioCount=p.bio.length;return`<div class="onboard-section"><p class="onboard-section-label">Basics</p><label for="display-name">${brand?'Project name':'Display name'} <em>*</em></label><input id="display-name" required maxlength="60" placeholder="${brand?'Your project name':'How should we call you?'}" value="${esc(p.name)}">${brand?`<label for="website">Project website <em>*</em></label><input id="website" type="url" required placeholder="https://yourproject.com" value="${esc(p.website)}">`:''}<div class="field-with-meta"><label for="bio">${brand?'About your project':'Short bio'} ${brand?'<em>*</em>':'<span class="hint">(optional)</span>'}</label><textarea id="bio" maxlength="240" ${brand?'required ':''}placeholder="${brand?'What are you building?':'Tell projects a little about yourself.'}">${esc(p.bio)}</textarea><span class="char-count" id="bio-count" aria-live="polite">${bioCount} / 240</span></div></div><div class="onboard-section"><p class="onboard-section-label">${brand?'Visual identity':'Profile photo'}</p><div class="profile-identity-card"><div class="avatar-wrap"><div class="avatar" style="${p.color?'background:'+p.color:''}">${avatarHTML()}</div><div class="avatar-actions"><button type="button" class="secondary" id="upload">${icon('upload')} Upload ${brand?'logo':'photo'}</button><button type="button" class="secondary" id="edit-avatar">${icon('edit')} Demo ${brand?'logo':'avatar'}</button></div><input type="file" id="photo-file" accept="image/png,image/jpeg,image/webp" hidden></div><p class="hint">PNG, JPG or WebP · up to 5 MB, or use a demo ${brand?'logo':'avatar'}.</p></div></div>`}
 function preferencesHTML(brand,pr){const meter=Math.min(pr.areas.length,3);return`<div class="pref-section"><div class="pref-section-head"><h3 class="pref-title">Connect a wallet</h3><span class="pref-badge">Optional</span></div><p class="hint pref-lead">Simulate a wallet link for payouts or campaign actions.</p><div class="wallet-options">${walletProviders.map((w,i)=>`<button type="button" class="wallet-option" data-wallet="${w}" aria-pressed="${pr.wallet?.provider===w}"><span class="wallet-symbol wallet-${i}">${['M','C','W'][i]}</span><span>${w}${w==='WalletConnect'?'<small class="wallet-sub">Various wallets supported</small>':''}</span><span class="wallet-action">${pr.wallet?.provider===w?'✓ Connected':'Connect ↗'}</span></button>`).join('')}</div>${pr.wallet?`<div class="connected-wallet" role="status"><span class="eyebrow">WALLET CONNECTED · MOCK</span><p>${esc(pr.wallet.provider)}</p><code>${esc(pr.wallet.address)}</code><button type="button" class="link-button" id="disconnect-wallet">Disconnect wallet</button></div>`:''}</div><div class="pref-section"><div class="pref-section-head"><h3 class="pref-title">Verticals</h3><span class="pref-badge pref-badge--required">Required · max 3</span></div><div class="vertical-meter" aria-hidden="true">${[0,1,2].map(i=>`<span class="${i<meter?'filled':''}"></span>`).join('')}</div><p class="hint pref-lead" aria-live="polite">${pr.areas.length?`Selected: ${esc(pr.areas.join(', '))}`:'Choose up to three focus areas.'}</p><div class="chips">${areaOptions.map(a=>`<button type="button" class="chip" data-area="${a}" aria-pressed="${pr.areas.includes(a)}">${a}</button>`).join('')}</div></div>${brand?`<div class="pref-section"><div class="pref-section-head"><h3 class="pref-title">Campaign goal</h3></div><label class="sr-only" for="goal">Primary campaign goal</label><select id="goal">${['Brand awareness','Community growth','Product launch','User acquisition'].map(v=>`<option ${pr.goal===v?'selected':''}>${v}</option>`).join('')}</select></div>`:''}`}
 function completeStepHTML(brand,p,pr){const social=Object.entries(state.socialLinks).map(([platform,link])=>`${esc(platform)} · ${esc(link.handle)}`).join('<br>');return`<div class="complete-hero"><div class="complete-avatar" style="${p.color&&!p.avatar?'background:'+p.color:''}">${avatarHTML()}</div><div><p class="eyebrow">${brand?'PROJECT APP':'CREATOR APP'} · DEMO READY</p><h2 class="complete-name">${esc(p.name||'Your profile')}</h2></div></div><div class="summary-box summary-box--rich"><div class="summary-row"><span>Account</span><strong>${brand?'Project / Brand':'Creator'}</strong></div><div class="summary-row"><span>Signed in via</span><strong>${esc(state.method)}</strong></div><div class="summary-row"><span>Email</span><strong>${esc(state.email||'—')}</strong></div><div class="summary-row"><span>Social</span><strong>${social||'None connected'}</strong></div><div class="summary-row"><span>Verticals</span><strong>${esc(pr.areas.join(', ')||'—')}</strong></div><div class="summary-row"><span>Wallet</span><strong>${pr.wallet?esc(pr.wallet.provider)+'<br><code class="summary-code">'+esc(pr.wallet.address)+'</code>':'Not connected'}</strong></div>${brand?`<div class="summary-row"><span>Campaign goal</span><strong>${esc(pr.goal)}</strong></div>`:''}</div><p class="hint">Onboarding complete. This prototype stops here; your demo account is not saved to a server.</p>`}
 function clearError(){const e=$('#error');if(e)e.textContent=''}
 function setStep(n){state.step=n;history.replaceState(null,'',`#${n===5?'complete':n+1}`);render();window.scrollTo(0,0);$('#step-title')?.focus()}
 function error(t){$('#error').textContent=t}
 function saveFields(){if(isAccessStep()&&$('#email'))state.email=$('#email').value;if(state.step===3){profile().name=$('#display-name').value;profile().bio=$('#bio').value;profile().website=$('#website')?.value||''}if(state.step===4&&$('#goal'))prefs().goal=$('#goal').value}
 function avatarHTML(){return profile().avatar?`<img class="uploaded" src="${esc(profile().avatar)}" alt="Your profile preview">`:profile().color?`<span>${esc((profile().name|| (isProject()?'P':'C')).slice(0,1).toUpperCase())}</span>`:icon('avatar-detail')}
 function render(){let brand=isProject(),p=profile(),pr=prefs();let title=isSigninAccess()?'Welcome to AllWeb3':['Account type','Welcome to AllWeb3','Social verification',brand?'Project profile':'Creator profile','Your preferences',brand?'Your project is ready.':'You’re ready to create.'][state.step];let subtitle=isSigninAccess()?`Your ${brand?'project':'creator'} journey starts here.`:['Tell us how you would like to use AllWeb3.',`Your ${brand?'project':'creator'} journey starts here.`,brand?'Connect a project channel to establish your brand’s presence.':'Connect a channel to match with relevant campaigns.',brand?'Introduce your project to the right creators.':'Set up your profile so projects can get to know you.',brand?'Find creators who share your project’s focus.':'Personalize the campaigns and opportunities you see.',brand?'Meet creators and bring your next campaign to life.':'Discover campaigns that fit your voice and interests.'][state.step];
 let body='';
 if(isAccessStep()){const signinIcons=isSigninAccess()?`<div class="divider">or continue with</div><div class="auth-icon-row" role="group" aria-label="Other sign-in options"><button type="button" class="auth-icon-btn" id="google" aria-label="Sign in with Google">${authIcon('google','Google')}</button><button type="button" class="auth-icon-btn" id="signin-wallet" aria-label="Sign in with Wallet">${authIcon('wallet','Wallet')}</button><button type="button" class="auth-icon-btn" id="signin-x" aria-label="Sign in with X">${authIcon('x','X')}</button><button type="button" class="auth-icon-btn" id="signin-youtube" aria-label="Sign in with YouTube">${authIcon('youtube','YouTube')}</button></div>`:'';const signupGoogle=state.mode==='signup'?`<button type="button" class="google" id="google">${authIcon('google','Google')} Sign up with Google</button><div class="divider">or continue with email</div>`:'';body=`${signupGoogle}<div class="auth-email-panel"><label for="email">Email address <em>*</em></label><input id="email" name="email" type="email" autocomplete="email" required placeholder="you@example.com" value="${esc(state.email)}"><p class="hint">${state.mode==='signup'?'We’ll verify your email with a one-time code. No password needed.':'Sign in to go directly to your portal. No verification code needed in this demo.'}</p></div>${signinIcons}<p class="switch-auth">${state.mode==='signup'?'Already have an account?':'New to AllWeb3?'} <button type="button" class="link-button" id="auth-mode">${state.mode==='signup'?'Sign in':'Sign up'}</button></p><p class="hint demo-footnote">Interactive demo · No real account or email is created.</p>`}
 if(state.mode==='signup'&&state.step===0)body=accountTypeHTML();
 if(state.step===2)body=socialVerificationHTML(brand);
 if(state.step===3)body=profileSetupHTML(brand,p);
 if(state.step===4)body=preferencesHTML(brand,pr);
 if(state.step===5)body=completeStepHTML(brand,p,pr);
 const showJourney=!isSigninAccess(),showProgress=state.mode==='signup'&&state.step<5,backHome=isSigninAccess()||(state.mode==='signup'&&state.step===0)||state.step===5,submitLabel=isSigninAccess()?'Sign in with email':state.mode==='signup'&&state.step===1?'Sign up with email':state.step===4?'Finish setup':state.step===5?'Explore demo app':'Next',submitDisabled=state.step===2&&!Object.keys(state.socialLinks).length,stepKicker=showProgress?`<p class="step-kicker"><span>Step ${state.step+1} of 5</span>${steps[state.step]}</p>`:'';
 $('#onboarding').innerHTML=`<div class="onboard-layout"><section class="onboard-panel"><div class="panel-head"><button class="back" id="back">‹ &nbsp;${backHome?'Back to home':'Back'}</button><span class="app-tag">${brand?'Project App':'Creator App'}</span></div>${stepKicker}<h1 id="step-title" tabindex="-1">${title}</h1><p class="subtitle">${subtitle}</p><form id="step-form"><div class="step-body">${body}<div id="error" class="error" role="alert"></div></div><div class="step-footer"><button class="primary" type="submit"${submitDisabled?' disabled':''}>${submitLabel} ${icon('arrow')}</button>${showProgress?`<div class="progress" aria-label="Step ${state.step+1} of 5">${steps.map((_,i)=>`<span class="${i===state.step?'active':i<state.step?'done':''}"></span>`).join('')}</div><div class="step-caption">${String(state.step+1).padStart(2,'0')} / 05 &nbsp; ${steps[state.step]}</div>`:state.step===5?'<button type="button" id="restart" class="link-button full">Start another walkthrough</button>':''}</div></form></section>${showJourney?`<aside class="journey"><a href="index.html" class="logo">ALLWEB3</a><h2>${brand?'Build your next chapter.':'Make your creativity count.'}</h2><p>${brand?'A few steps to connect your project with creators who move it forward.':'A few steps to connect your talent with the right opportunities.'}</p><ol>${steps.map((s,i)=>`<li class="${i===state.step?'current':''}" ${i===state.step?'aria-current="step"':''}"><span>${i<state.step?'✓':i+1}</span>${s}</li>`).join('')}</ol><p class="demo-note">Interactive onboarding prototype<br>Email, Google, and social verification are simulated.</p></aside>`:''}</div><footer class="onboard-footer">${['Terms','Privacy','Docs'].map(t=>`<button type="button" data-info="${t==='Docs'?'docs':t}">${t}</button>`).join(icon('dot'))}<span class="footer-language">${icon('globe')} English ${icon('chevron')}</span></footer>`;
 $('#back').onclick=()=>{saveFields();if(backHome)location.href='index.html';else setStep(state.step-1)};
 $$('[data-info]').forEach(b=>b.onclick=()=>info(b.dataset.info));
 $('#step-form').onsubmit=e=>{e.preventDefault();saveFields();if(isSigninAccess()){state.method='Email';location.href='portal.html'}else if(state.mode==='signup'&&state.step===0)setStep(1);else if(state.mode==='signup'&&state.step===1){state.method='Email';showOTP()}else if(state.step===2){if(!Object.keys(state.socialLinks).length)return error('Connect at least one social channel to continue.');setStep(3)}else if(state.step===3){if(!p.name.trim())return error(brand?'Enter a project name to continue.':'Enter a display name to continue.');if(brand&&!p.bio.trim())return error('Tell us about your project to continue.');if(!p.avatar&&!p.color)return error(`Upload a ${brand?'logo':'photo'} or choose a demo ${brand?'logo':'avatar'}.`);setStep(4)}else if(state.step===4){if(!pr.areas.length)return error('Select at least one vertical.');setStep(5)}else showDestination()};
 if(isAccessStep()){$('#auth-mode').onclick=()=>{saveFields();const toSignup=state.mode==='signin';state.mode=toSignup?'signup':'signin';if(state.mode==='signin')state.step=0;else if(toSignup)state.step=0;render()};$('#google').onclick=showGoogle;$('#email')?.addEventListener('input',clearError);if(isSigninAccess()){$('#signin-wallet').onclick=showSignInWalletPicker;$('#signin-x').onclick=()=>showSignInSocial('X / Twitter','X','𝕏');$('#signin-youtube').onclick=()=>showSignInSocial('YouTube','YouTube','▶')}}
 $$('[data-account]').forEach(b=>b.onclick=()=>{if(state.role!==b.dataset.account){state.role=b.dataset.account;state.socialLinks={}}render()});
 $$('[data-social-connect]').forEach(b=>b.onclick=()=>verifySocial(b.dataset.socialConnect));
 $$('[data-social-disconnect]').forEach(b=>b.onclick=()=>{delete state.socialLinks[b.dataset.socialDisconnect];render()});
 if(state.step===3){$('#upload').onclick=()=>$('#photo-file').click();$('#photo-file').onchange=e=>{let f=e.target.files[0];if(!f)return;if(!['image/png','image/jpeg','image/webp'].includes(f.type)||f.size>5*1024*1024)return error('Choose a PNG, JPG, or WebP image smaller than 5 MB.');saveFields();let reader=new FileReader();reader.onload=()=>{let test=new Image();test.onload=()=>{p.avatar=reader.result;clearError();render()};test.onerror=()=>error('This image could not be opened. Please choose another file.');test.src=reader.result};reader.readAsDataURL(f)};$('#edit-avatar').onclick=()=>{saveFields();openModal(`<h2>Choose a demo ${brand?'logo':'avatar'}</h2><p>Pick a color. We’ll use the first letter of your name.</p><div class="swatches">${['#baff7c','#80d8ff','#c8a2ff','#ffc98a'].map(c=>`<button aria-label="Choose ${c}" data-color="${c}" style="background:${c}"></button>`).join('')}</div>`);$$('[data-color]').forEach(b=>b.onclick=()=>{p.color=b.dataset.color;p.avatar='';closeModal();render()})};$('#bio')?.addEventListener('input',e=>{const n=e.target.value.length;const c=$('#bio-count');if(c)c.textContent=`${n} / 240`;clearError()});$$('#display-name,#website').forEach(el=>el?.addEventListener('input',clearError))}
 $$('[data-area]').forEach(b=>b.onclick=()=>{saveFields();let a=b.dataset.area;if(pr.areas.includes(a))pr.areas=pr.areas.filter(x=>x!==a);else if(pr.areas.length<3)pr.areas.push(a);else return error('You can select up to 3 verticals. Deselect one to add another.');render()});
 $$('[data-wallet]').forEach(b=>b.onclick=()=>{saveFields();connectWallet(b.dataset.wallet)});
 $('#disconnect-wallet')?.addEventListener('click',()=>{saveFields();pr.wallet=null;render()});
 $('#restart')?.addEventListener('click',()=>location.href='index.html');
 }
 function walletOptionsHTML(attr){return walletProviders.map((w,i)=>`<button type="button" class="wallet-option" ${attr}="${w}"><span class="wallet-symbol wallet-${i}">${['M','C','W'][i]}</span><span>${w}${w==='WalletConnect'?'<small class="wallet-sub">Various wallets supported</small>':''}</span><span class="wallet-action">Connect ↗</span></button>`).join('')}
 function completeSignIn(method,email){state.method=method;if(email)state.email=email;location.href='portal.html'}
 function showSignInWalletPicker(){openModal(`<h2>Sign in with wallet</h2><p>Choose a wallet provider to continue.</p><div class="wallet-options modal-wallet-options">${walletOptionsHTML('data-signin-wallet')}</div><p class="hint">Demo only. No extension, signature, or real wallet is required.</p>`);$$('[data-signin-wallet]').forEach(b=>b.onclick=()=>connectWallet(b.dataset.signinWallet,{signIn:true}))}
 function showSignInSocial(platformKey,label,mark){const account=mockSocialConnection(platformKey);openModal(`<div class="modal-icon">${mark}</div><h2>Sign in with ${esc(label)}</h2><p>Mock ${esc(label)} sign-in · continue to AllWeb3</p><button type="button" class="account-row" id="mock-social-signin"><span>${mark}</span><div>${esc(account.handle)}<small>${esc(account.followers)} · demo account</small></div></button><p class="hint">This account is a placeholder. ${esc(label)} is not contacted.</p>`);$('#mock-social-signin').onclick=()=>{closeModal();completeSignIn(label,account.handle)}}
 function connectWallet(provider,opts={}){const addresses={'MetaMask':'0x7A12bC3456De7890fA1234567890bCDeF1234567','Coinbase Wallet':'0xC01234567890abCDef1234567890AbCDeF123456','WalletConnect':'0xA01234567890abCDef1234567890AbCDeF123456'};const extra=provider==='WalletConnect'?'<p class="hint">WalletConnect can route to many mobile and browser wallets in a real app.</p>':'';openModal(`<div class="modal-icon">◇</div><h2>Connect ${esc(provider)}</h2><p>Mock wallet connection</p><p>This demo will display a sample wallet address. No wallet permissions or signatures are requested.</p>${extra}<button type="button" class="primary full" id="confirm-wallet">Connect mock wallet</button>`);$('#confirm-wallet').onclick=()=>{$('#confirm-wallet').disabled=true;$('#confirm-wallet').textContent='Connecting…';modalTimer=setTimeout(()=>{const wallet={provider,address:addresses[provider]};prefs().wallet=wallet;closeModal();if(opts.signIn)completeSignIn(`Wallet · ${provider}`,wallet.address);else render()},900)}}
 function showOTP(){openModal(`<div class="modal-icon">✉</div><h2>Check your email</h2><p>Enter the six-digit code for <strong>${esc(state.email)}</strong>.</p><p class="hint">Demo mode: any 6 digits work, for example 123456. No email is sent.</p><form id="otp-form"><div class="otp-row">${Array.from({length:6},(_,i)=>`<input aria-label="Digit ${i+1}" inputmode="numeric" pattern="[0-9]" maxlength="1" ${i===0?'autocomplete="one-time-code"':''} required>`).join('')}</div><p id="otp-status" role="status" class="hint"></p><button class="primary full" type="submit">Verify & continue ${icon('arrow')}</button></form><button class="link-button full" id="resend">Resend code</button>`);const inputs=$$('.otp-row input');inputs[0].focus();inputs.forEach((input,i)=>{input.oninput=()=>{input.value=input.value.replace(/\D/g,'').slice(-1);if(input.value)inputs[i+1]?.focus()};input.onkeydown=e=>{if(e.key==='Backspace'&&!input.value)inputs[i-1]?.focus();if(e.key==='ArrowLeft')inputs[i-1]?.focus();if(e.key==='ArrowRight')inputs[i+1]?.focus()};input.onpaste=e=>{e.preventDefault();let code=e.clipboardData.getData('text').replace(/\D/g,'').slice(0,6);[...code].forEach((d,j)=>{if(inputs[i+j])inputs[i+j].value=d});inputs[Math.min(i+code.length,5)].focus()}}); $('#otp-form').onsubmit=e=>{e.preventDefault();if(inputs.every(i=>/^\d$/.test(i.value))){closeModal();setStep(2)}};$('#resend').onclick=()=>{$('#otp-status').textContent='New mock code ready. Enter any six digits.';inputs.forEach(i=>i.value='');inputs[0].focus()}}
 function showGoogle(){openModal(`<div class="modal-icon">G</div><h2>Choose an account</h2><p>Mock Google ${state.mode==='signup'?'sign-up':'sign-in'} · continue to AllWeb3</p><button class="account-row" id="mock-google"><span>D</span><div>Demo ${isProject()?'Brand':'Creator'}<small>${isProject()?'brand':'creator'}@example.com</small></div></button><p class="hint">This account is a placeholder. Google is not contacted.</p>`);$('#mock-google').onclick=()=>{state.method='Google';state.email=`${isProject()?'brand':'creator'}@example.com`;closeModal();if(state.mode==='signin')location.href='portal.html';else setStep(2)}}
 function verifySocial(platform){if(!platform||state.socialLinks[platform])return;openModal(`<div class="center"><div class="spinner"></div><h2>Mock Social verification</h2><p>Connecting your ${esc(platform)} ${isProject()?'project channel':'account'}…</p><p class="hint">This takes a moment. No permissions are requested.</p><div role="status" aria-live="polite" id="social-status">Verifying demo connection</div></div>`);modalTimer=setTimeout(()=>{$('#social-status').textContent='✓ Connection verified';modalTimer=setTimeout(()=>{state.socialLinks[platform]=mockSocialConnection(platform);closeModal();render()},650)},1300)}
 function showDestination(){openModal(`<div class="modal-icon">✓</div><h2>Welcome to the ${isProject()?'Project':'Creator'} App</h2><p>${isProject()?'Your next step would be to create a campaign and invite creators.':'Your next step would be to browse matching campaigns and apply.'}</p><div class="summary-box"><strong>${isProject()?'Create your first campaign':'Discover your first campaign'}</strong><p>Recommended verticals: ${esc(prefs().areas.join(', '))}</p></div><p class="hint">This is the final destination preview of the onboarding mockup.</p><button class="primary full" id="home">Return to home</button>`);$('#home').onclick=()=>location.href='index.html'}
 render();
}
